name: build Workflow
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        type: environment

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: build
      run: |
        # Add your deployment script or commands for the dev environment
          echo "build script"

  Deploy:
    needs: build
    strategy:
      fail-fast: true
      matrix:
        target: [dev, prod]
        runner: [ubuntu-latest,windows-latest]
    uses: ./.github/workflows/deployment.yml
    with:
      target-env: ${{ matrix.target }}
      target-runner: ${{ matrix.runner }}
    secrets: inherit

  Deploy-ab:
    needs: build
    strategy:
      fail-fast: true
      matrix:
        target: [dev, prod]
        runner: [ubuntu-latest,windows-latest]
    uses: ./.github/workflows/deployment2.yml
    with:
      target-env: ${{ matrix.target }}
      target-runner: ${{ matrix.runner }}
    secrets: inherit
