name: Reusable-2 workflow

on:
  workflow_call:
    inputs:
      target-env:
        required: true
        type: string

jobs:
 deploy-ab:
    name: Deploy to ${{ inputs.target-env }}
    runs-on: ${{ inputs.target-env }}
    # continue-on-error: true
    environment:
      name: ${{ inputs.target-env }}
      # url: ${{ steps.step_id.outputs.url_output }}
    env:
      name: ${{vars.RUNNER}}
    steps:
      - run: echo "${{env.name}}"
      - name: Environment Approval
        id: approval
        run: echo "Check approval status"
      - name: "Deploy to Prod"
        if: ${{ steps.approval.outputs.approved == 'true' }}
        run: |
          # Add your deployment script or commands for the chosen environment
          echo "Deploying to ${{ inputs.target-env }} and ${{ inputs.target-env }}"
