name: Reusable workflow

on:
  workflow_call:
    inputs:
      target-env:
        required: true
        type: string
      target-ap: 
        required: true
        type: string
      target-dp: 
        required: true
        type: string

jobs:
  deploy:
    name: Deploy to ${{ inputs.target-env }}
    runs-on: ${{ inputs.target-ap }}
    environment:
      name: ${{ inputs.target-env }}
      # url: ${{ steps.step_id.outputs.url_output }}
    env:
      name: ${{vars.RUNNER}}
    steps:
      - run: echo "${{env.name}}"
      # - name: Set up .NET
      #   uses: actions/setup-dotnet@1
      #   with:
      #     dotnet-version: '2'
      - name: "Deploy to ${{ inputs.target-ap }}"
        run: |
          # Add your deployment script or commands for the chosen environment
          echo "Deploying to ${{ inputs.target-env }} and ${{ inputs.target-ap }}"


  deploy-DB:
    name: Deploy to ${{ inputs.target-env }}
    runs-on: ${{ inputs.target-dp }}
    environment:
      name: ${{ inputs.target-env }}
      # url: ${{ steps.step_id.outputs.url_output }}
    env:
      name2: ${{vars.RUNNER}}
    steps:
      - run: echo "${{env.name2}}"
      # - name: Set up .NET
      #   uses: actions/setup-dotnet@1
      #   with:
      #     dotnet-version: '2'
      - name: "Deploy to ${{ inputs.target-dp }}"
        run: |
          # Add your deployment script or commands for the chosen environment
          echo "Deploying to ${{ inputs.target-env }} and ${{ inputs.target-dp }}"






# name: Env Workflow
# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:
#     inputs:
#       environment:
#         description: 'Select environment'
#         required: true
#         type: environment

# jobs:
#   build:
#     runs-on: windows-2019
#     steps:
#     - name: build
#       run: |
#         # Add your deployment script or commands for the dev environment
#           echo "build script"
#   deploy-APP:
#     needs: build
#     runs-on: ${{ matrix.environment }}
#     strategy:
#       matrix:
#         environment: [windows-2019, windows-latest]
#       fail-fast: true
#     environment:
#       name: ${{ matrix.environment }}
#     steps:
#       - run: echo "🎉 target evn ${{ matrix.environment}}"
#       - run: echo "${{env.name}}"
#       - name: Deploy to ${{ matrix.environment }}
#         if: matrix.environment == 'windows-2019'
#         run: |
#           # Add your deployment script or commands for the chosen environment
#           echo "Deploying to ${{ matrix.environment }}"

#       - name: Deploy to ${{ matrix.environment }}
#         if: matrix.environment == 'windows-latest'
#         run: |
#           # Add your deployment script or commands for the chosen environment
#           echo "Deploying to ${{ matrix.environment }}"


          

