name: Reusable-2 workflow

on:
  workflow_call:
    inputs:
      target-env:
        required: true
        type: string
      target-runner: 
        required: true
        type: string

jobs:
 deploy-ab:
    name: Deploy to ${{ inputs.target-env }}
    runs-on: ${{ inputs.target-runner }}
    environment:
      name: ${{ inputs.target-env }}
      # url: ${{ steps.step_id.outputs.url_output }}
    steps:
      - name: "Deploy to Azure Prod"
        if: inputs.target-env == 'prod' && inputs.target-runner == 'ubuntu-latest'
        run: |
          # Add your deployment script or commands for the chosen environment
          echo "Deploying to ${{ inputs.target-env }} and ${{ inputs.target-runner }}"
