name: fetch-other repo

on:
  push:
    branches:
      - main
  # workflow_dispatch:
  #   inputs:
  #     environment:
  #       description: 'Select environment (dev or prod)'
  #       required: true
  #       default: 'dev'
  #       type: environment

jobs:
  build-dev:
    runs-on: local
    # if: ${{ github.event.inputs.environment == 'dev' }}
    
    steps:
    - run: Get-Service -Name "actions.runner.abhishekmachag-environments.DESKTOP-CM9BQLR"
    - run: Start-Service -Name "actions.runner.abhishekmachag-environments.DESKTOP-CM9BQLR" -PassThru
    - run: Stop-Service -Name "actions.runner.abhishekmachag-environments.DESKTOP-CM9BQLR" -PassThru
    - run: Start-Sleep -Seconds 3

    # - name: Checkout First Repository
    #   uses: actions/checkout@v3
    #   with:
    #     repository: abhishekmachag/environments
    #     ref: main
    #     path: ${{ github.workspace }}/environments
    #     token: ${{ secrets.GITHUB_TOKEN }}

    # - run: Get-ChildItem
    # - run: Get-Location
    # - name: Checkout Second Repository
    #   run: git clone https://abhishekmachag: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@github.com/abhishekmachag/msbuild.git
    #   # uses: actions/checkout@v3
    #   # with:
    #   #   repository: abhishekmachag/msbuild
    #   #   ref: master
    #   #   path: ${{ github.workspace }}\msbuild
    #   #   token: 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

    # - run: Get-ChildItem
    # - run: Get-Location
