name: triggerpoint

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment (dev or prod)'
        required: true
        default: 'dev'
        type: environment

jobs:
  build-dev:
    runs-on: windows-2019
    if: ${{ github.event.inputs.environment == 'dev' }}

    outputs:
      env: CONTINUE_JOBS

    steps:
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '5'

    # Your build steps go here

  deploy-dev:
    runs-on: windows-2019
    if: ${{ needs.build-dev.outputs.CONTINUE_JOBS == 'true' }}
    needs: build-dev
    environment:
      name: dev

    steps:
    - name: Deploy to Dev
      run: |
        # Add your deployment script or commands for the dev environment
        echo "Deploying to Dev environment..."
