name: Combined Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment (dev or prod)'
        required: true
        default: 'dev'

jobs:
  build-and-deploy-dev:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'dev' }}

    steps:
    # - name: Checkout Repository
    #   uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '5'  # You can adjust this version

    # - name: Restore dependencies
    #   run: dotnet restore

    # - name: Build application
    #   run: dotnet build --configuration Release

    # - name: Publish artifact
    #   run: dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)

    - name: Deploy to Dev
      run: |
        # Add your deployment script or commands for the dev environment
        echo "Deploying to Dev environment..."

  build-and-deploy-prod:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'prod' }}

    steps:
    # - name: Checkout Repository
    #   uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '5'  # You can adjust this version

    # - name: Restore dependencies
    #   run: dotnet restore

    # - name: Build application
    #   run: dotnet build --configuration Release

    # - name: Publish artifact
    #   run: dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)

    - name: Deploy to Prod
      run: |
        # Add your deployment script or commands for the prod environment
        echo "Deploying to Prod environment..."




# name: 'Deploy ASP.NET Core app to Azure Web App'

# on:
#   # push:
#   #   branches:
#   #     - "main"
#   workflow_dispatch:
#     inputs:
#       environment:
#         # description: "pipeline start manual
#         type: environmnet
#         required: true
 
# env:
#   DOTNET_VERSION: '3.1.404'


# jobs:
#   build-and-publish:
#     runs-on: ubuntu-latest
#     environment:
#       name: prod
#     steps:

#       # Checkout the repo
#       - uses: actions/checkout@master

#   build:
#     runs-on: ubuntu-latest
#     needs: build-and-publish
#     environment:
#       name: prod
    
#     steps:
#       # Setup .NET Core SDK
#       - name: Setup .NET Core
#         uses: actions/setup-dotnet@v3
#         with:
#           dotnet-version: ${{ env.DOTNET_VERSION }}



#   build-and-publish-dev:
#     runs-on: ubuntu-latest
#     environment:
#       name: dev
#     steps:

#       # Checkout the repo
#       - uses: actions/checkout@master

#   build-dev:
#     runs-on: ubuntu-latest
#     needs: build-and-publish-dev
#     environment:
#       name: dev
    
#     steps:
#       # Setup .NET Core SDK
#       - name: Setup .NET Core
#         uses: actions/setup-dotnet@v3
#         with:
#           dotnet-version: ${{ env.DOTNET_VERSION }}










          

      # Run dotnet build and publish
      # - name: dotnet build and publish
      #   working-directory: 'app'
      #   run: |
      #     dotnet restore
      #     dotnet build --configuration Release
      #     dotnet publish -c Release -o './published-app'

      # # Publish artifact
      # - name: Publish artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: published-app
      #     path: './app/published-app'

  # deploy-dev:
  #   runs-on: 'ubuntu-latest'
  #   environment: 'dev'
  #   needs: build-and-publish
  #   steps:

  #     # Download published artifact
  #     - name: Download artifact
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: published-app
  #         path: './published-app'

  #     # Deploy to web app
  #     - name: Deploy to Azure WebApp
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: app-cloudlumberjack-dev
  #         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  #         package: './published-app'

  # deploy-prod:
  #   runs-on: 'ubuntu-latest'
  #   environment: 'prod'
  #   needs: [build-and-publish, deploy-dev]
  #   steps:

  #     # Download published artifact
  #     - name: Download artifact
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: published-app
  #         path: './published-app'

  #     # Deploy to web app
  #     - name: Deploy to Azure WebApp
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: app-cloudlumberjack-prod
  #         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  #         package: './published-app'
