name: Combined Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment (dev or prod)'
        required: true
        default: 'dev'
        type: environment

jobs:
  build-dev:
    runs-on: windows-2019
    if: ${{ github.event.inputs.environment == 'dev' }}

    steps:
    # - name: Checkout Repository
    #   uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '5'  # You can adjust this version

    # - name: Restore dependencies
    #   run: dotnet restore

    # - name: Build application
    #   run: dotnet build --configuration Release

    # - name: Publish artifact
    #   run: dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)
  deploy-dev:
    runs-on: windows-2019
    needs: build-dev
    environment:
      name: dev
    
    steps:
    - name: Deploy to Dev
      run: |
        # Add your deployment script or commands for the dev environment
        echo "Deploying to Dev environment..."

  build-prod:
    runs-on: windows-2019
    if: ${{ github.event.inputs.environment == 'prod' }}

    steps:
    # - name: Checkout Repository
    #   uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '5'  # You can adjust this version

    # - name: Restore dependencies
    #   run: dotnet restore

    # - name: Build application
    #   run: dotnet build --configuration Release

    # - name: Publish artifact
    #   run: dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)


  deploy-prod:
    runs-on: windows-2019
    needs: build-prod
    environment:
      name: prod
    steps:
      - name: Deploy to Prod
        run: |
          # Add your deployment script or commands for the prod environment
          echo "Deploying to Prod environment..."

